reorder_imports = true
reorder_imported_names = true
reorder_imports_in_group = true
normalize_comments = true
format_strings = true
condense_wildcard_suffixes = true
chain_split_single_child = true
struct_field_align_threshold = 20